version: '3'
services:
  datadog:
    image: datadog/agent:latest
    environment:
     - DD_API_KEY=858af784e234d903aec234c68a0af14e
     - DD_PROCESS_AGENT_ENABLED=true
     - DD_LOGS_ENABLED=true
     - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
     - DOCKER_CONTENT_TRUST=1
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
  login-server:
    build: 
        context: ./
        dockerfile: ./login-server/Dockerfile
    depends_on:
       - database
       - adminer
       - apache
       - proxy
    ports:
       - 6900:6900

  char-server:
      build:
         context: ./
         dockerfile: ./char-server/Dockerfile
      depends_on:
         - login-server
      ports:
         - 6121:6121

  map-server:
      build:
         context: ./
         dockerfile: ./map-server/Dockerfile
      depends_on:
         - char-server
      ports:
         - 5121:5121
 
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ragnarok
    volumes:
            - ~/mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  apache:
     build:
       context: ./
       dockerfile: ./apache/Dockerfile
     ports:
       - 80:80

  proxy:
     build:
        context: ./
        dockerfile: ./proxy/Dockerfile
     ports:
        - 5999:5999

